# Generated by Django 4.2.4 on 2023-08-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
